remote_theme: pmarsceill/just-the-docs
title: CBS-beta
description: Beta-release of the CBS framework
repository: "plancomps/CBS-beta"
# baseurl: "/CBS-beta"
# Aux links for the upper right navigation
aux_links:
  "CBS-beta on GitHub":
    - "//github.com/plancomps/CBS-beta"
# logo: "/assets/images/PLanCompS-150.png"
plugins:
    - jekyll-seo-tag
compress_html:
  blanklines: true
# Set the search token separator
search_tokenizer_separator: /[\s/]+/
