remote_theme: pdmosses/just-the-docs@combination-rec-nav
# remote_theme: pmarsceill/just-the-docs@0.3.3 allows only 3 levels of navigation
title: CBS-beta
description: Beta-release of the CBS framework

baseurl: "/CBS-beta"
url: "https://plancomps.github.io"

aux_links:
  "CBS-beta on GitHub":
    - "//github.com/plancomps/CBS-beta"

# logo: "/assets/images/PLanCompS-150.png"

collections:
  docs:
    output: true
  math:
    output: true

just_the_docs:
  collections:
    docs:
      name: Plain
      nav_fold: true
    math:
      name: Pretty
      nav_fold: true
      search_exclude: true

# Color scheme supports "dark", "light", and your custom schemes:
# color_scheme: nil                # default: light
# To add a button to switch all pages to a different scheme:
toggle_color_scheme: dark          # default: nil (no toggle button)
# To display the toggle button only on one page:
# toggle_page_url: "/"               # default: nil (display on all pages)
# To toggle automatically when the system mode preference changes:
# toggle_auto_mode: true             # default: nil (manual toggle)
# To set the button text for toggling and reverting:
toggle_text_1: "&#x263d;" # default: "&rarr; Dark Mode"
toggle_text_2: "&#x263c;" # default: "&rarr; Light Mode"

callouts:
  note:
    title: Note
    color: purple

exclude:
  - "profiles/"
  - "logs/"
  - makefile
  - sunshine2.jar
  - "Languages-beta/*/*/Funcons-beta"
  - "Unstable-Funcons-beta/Funcons-beta"
  - "Unstable-Languages-beta/*/*/Unstable-Funcons-beta"
  - "*/target"
  - "*/*/target"
  - "*/*/*/target"
  - "*/*/*/*/target"
  - "*/*/*/*/*/target"
  - "*/*/*/*/tests"
  - "*/*/*/*/*/tests"
  - "*/*/*/*.tex"
  - "*/*/*/*/*.tex"
  - "*/*/*/*/*/*.tex"

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

footer_content: ""

nav_next_prev: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

compress_html:
  blanklines: false

nav_next_prev: true

# Navigation order for generated funcons files

defaults:
  -
    scope: {path: docs, type: pages}
    values: {layout: default}
  -
    scope: {type: docs}
    values: {layout: default}
  -
    scope: {type: math}
    values: {layout: default}
  -
    scope: {path: "*/index.md", type: pages}
    values: {layout: default}

# Funcons-beta

  # Computations

  # Normal
  - 
    scope: {path: "*/Funcons-beta/Computations/Normal/Flowing"}
    values: {nav_order: 1}
  - 
    scope: {path: "*/Funcons-beta/Computations/Normal/Giving"}
    values: {nav_order: 2}
  - 
    scope: {path: "*/Funcons-beta/Computations/Normal/Binding"}
    values: {nav_order: 3}
  - 
    scope: {path: "*/Funcons-beta/Computations/Normal/Generating"}
    values: {nav_order: 4}
  - 
    scope: {path: "*/Funcons-beta/Computations/Normal/Storing"}
    values: {nav_order: 5}
  - 
    scope: {path: "*/Funcons-beta/Computations/Normal/Linking"}
    values: {nav_order: 6}
  - 
    scope: {path: "*/Funcons-beta/Computations/Normal/Interacting"}
    values: {nav_order: 7}

  # Abnormal
  - 
    scope: {path: "*/Funcons-beta/Computations/Abnormal/Abrupting"}
    values: {nav_order: 1}
  - 
    scope: {path: "*/Funcons-beta/Computations/Abnormal/Failing"}
    values: {nav_order: 2}
  - 
    scope: {path: "*/Funcons-beta/Computations/Abnormal/Throwing"}
    values: {nav_order: 3}
  - 
    scope: {path: "*/Funcons-beta/Computations/Abnormal/Returning"}
    values: {nav_order: 4}
  - 
    scope: {path: "*/Funcons-beta/Computations/Abnormal/Breaking"}
    values: {nav_order: 5}
  - 
    scope: {path: "*/Funcons-beta/Computations/Abnormal/Continuing"}
    values: {nav_order: 6}
  - 
    scope: {path: "*/Funcons-beta/Computations/Abnormal/Controlling"}
    values: {nav_order: 7}

  # Values

  # Primitive
  - 
    scope: {path: "*/Funcons-beta/Values/Primitive/Booleans"}
    values: {nav_order: 1}
  - 
    scope: {path: "*/Funcons-beta/Values/Primitive/Integers"}
    values: {nav_order: 2}
  - 
    scope: {path: "*/Funcons-beta/Values/Primitive/Floats"}
    values: {nav_order: 3}
  - 
    scope: {path: "*/Funcons-beta/Values/Primitive/Characters"}
    values: {nav_order: 4}
  - 
    scope: {path: "*/Funcons-beta/Values/Primitive/Null"}
    values: {nav_order: 5}

  # Composite

  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Sequences"}
    values: {nav_order: 1}
  
  - # Datatypes
    scope: {path: "*/Funcons-beta/Values/Composite/Datatypes"}
    values: {nav_order: 2}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Tuples"}
    values: {nav_order: 3}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Lists"}
    values: {nav_order: 4}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Strings"}
    values: {nav_order: 5}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Vectors"}
    values: {nav_order: 6}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Trees"}
    values: {nav_order: 7}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/References"}
    values: {nav_order: 8}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Records"}
    values: {nav_order: 9}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Variants"}
    values: {nav_order: 10}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Classes"}
    values: {nav_order: 11}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Objects"}
    values: {nav_order: 12}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Bits"}
    values: {nav_order: 13}
  - # Built-in
    scope: {path: "*/Funcons-beta/Values/Composite/Sets"}
    values: {nav_order: 14}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Maps"}
    values: {nav_order: 15}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Multisets"}
    values: {nav_order: 16}
  - 
    scope: {path: "*/Funcons-beta/Values/Composite/Graphs"}
    values: {nav_order: 17}

  # Abstraction
  
  - 
    scope: {path: "*/Funcons-beta/Values/Abstraction/Generic"}
    values: {nav_order: 1}
  - 
    scope: {path: "*/Funcons-beta/Values/Abstraction/Thunks"}
    values: {nav_order: 2}
  - 
    scope: {path: "*/Funcons-beta/Values/Abstraction/Functions"}
    values: {nav_order: 3}
  - 
    scope: {path: "*/Funcons-beta/Values/Abstraction/Patterns"}
    values: {nav_order: 4}
