remote_theme: pdmosses/just-the-docs@rec-nav
# remote_theme: pmarsceill/just-the-docs
title: CBS-beta
description: Beta-release of the CBS framework

baseurl: "/CBS-beta" # the subpath of your site, e.g. /blog
url: "https://plancomps.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# Aux links for the upper right navigation
aux_links:
  "CBS-beta on GitHub":
    - "//github.com/plancomps/CBS-beta"
# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/PLanCompS-150.png"

# permalink: pretty
exclude:
  - "profiles/"

# Set the search token separator
# search_tokenizer_separator: /[\s/]+/

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# Enable or disable heading anchors
# heading_anchors: true

# Makes Aux links open in a new tab. Default is false
# aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # N.B. numbers are sorted lexicographically
nav_sort: case_sensitive # Capital letters sorted before lowercase, numbers by value

# Display navigation expanders
nav_expanders: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
footer_content: ""

# Footer last edited timestamp
# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub"
# gh_edit_repository: "https://github.com/plancomps/CBS-beta" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
# color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-remote-theme
#   - jekyll-seo-tag

# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false
