remote_theme: pdmosses/just-the-docs@combination-rec-nav
# remote_theme: pmarsceill/just-the-docs
title: CBS-beta
description: Beta-release of the CBS framework

baseurl: "/CBS-beta" # the subpath of your site, e.g. /blog
url: "https://plancomps.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# Aux links for the upper right navigation
aux_links:
  "CBS-beta on GitHub":
    - "//github.com/plancomps/CBS-beta"
# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/PLanCompS-150.png"

# permalink: pretty
exclude:
  - "profiles/"
  - "Languages-beta/IMP/IMP-cbs/Funcons-beta/"
  - "Languages-beta/IMP/IMP-cbs/target/"
  - "Languages-beta/MiniJava/MiniJava-cbs/Funcons-beta/"
  - "Languages-beta/MiniJava/MiniJava-cbs/target/"
  - "Languages-beta/SIMPLE/SIMPLE-cbs/Funcons-beta/"
  - "Languages-beta/SIMPLE/SIMPLE-cbs/target/"
  - "Languages-beta/SL/SL-cbs/Funcons-beta/"
  - "Languages-beta/SL/SL-cbs/target/"
  - "Languages-beta/OCaml-Light/OC-L-cbs/Funcons-beta/"
  - "Languages-beta/OCaml-Light/OC-L-cbs/target/"
  - "Unstable-Funcons-beta/Funcons-beta/"
  - "Unstable-Languages-beta/IMP-Plus-Plus/IMPPP-cbs/Unstable-Funcons-beta/"
  - "Unstable-Languages-beta/IMP-Plus-Plus/IMPPP-cbs/target/"
  - "Unstable-Languages-beta/LangDev-2019/LD-cbs/Unstable-Funcons-beta/"
  - "Unstable-Languages-beta/LangDev-2019/LD-cbs/target/"
  - "Unstable-Languages-beta/SIMPLE-Threads/SIMPLE-THR-cbs/Unstable-Funcons-beta/"
  - "Unstable-Languages-beta/SIMPLE-Threads/SIMPLE-THR-cbs/target/"

# Set the search token separator
# search_tokenizer_separator: /[\s/]+/

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# Enable or disable heading anchors
# heading_anchors: true

# Makes Aux links open in a new tab. Default is false
# aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # N.B. numbers are sorted lexicographically
nav_sort: case_sensitive # Capital letters sorted before lowercase, numbers by value

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
footer_content: ""

# Footer last edited timestamp
# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub"
# gh_edit_repository: "https://github.com/plancomps/CBS-beta" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
# color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
#   - jekyll-seo-tag

# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false

nav_next_prev: true

# nav_cache: false

# Navigation order for generated funcons files

defaults:
  -
    scope: {path: docs, type: pages}
    values: {layout: default}

# Funcons-beta

  # Computations

  # Normal
  - 
    scope: {path: Funcons-beta/Computations/Normal/Flowing}
    values: {nav_order: 1}
  - 
    scope: {path: Funcons-beta/Computations/Normal/Giving}
    values: {nav_order: 2}
  - 
    scope: {path: Funcons-beta/Computations/Normal/Binding}
    values: {nav_order: 3}
  - 
    scope: {path: Funcons-beta/Computations/Normal/Generating}
    values: {nav_order: 4}
  - 
    scope: {path: Funcons-beta/Computations/Normal/Storing}
    values: {nav_order: 5}
  - 
    scope: {path: Funcons-beta/Computations/Normal/Linking}
    values: {nav_order: 6}
  - 
    scope: {path: Funcons-beta/Computations/Normal/Interacting}
    values: {nav_order: 7}

  # Abnormal
  - 
    scope: {path: Funcons-beta/Computations/Abnormal/Abrupting}
    values: {nav_order: 1}
  - 
    scope: {path: Funcons-beta/Computations/Abnormal/Failing}
    values: {nav_order: 2}
  - 
    scope: {path: Funcons-beta/Computations/Abnormal/Throwing}
    values: {nav_order: 3}
  - 
    scope: {path: Funcons-beta/Computations/Abnormal/Returning}
    values: {nav_order: 4}
  - 
    scope: {path: Funcons-beta/Computations/Abnormal/Breaking}
    values: {nav_order: 5}
  - 
    scope: {path: Funcons-beta/Computations/Abnormal/Continuing}
    values: {nav_order: 6}
  - 
    scope: {path: Funcons-beta/Computations/Abnormal/Controlling}
    values: {nav_order: 7}

  # Values

  # Primitive
  - 
    scope: {path: Funcons-beta/Values/Primitive/Booleans}
    values: {nav_order: 1}
  - 
    scope: {path: Funcons-beta/Values/Primitive/Integers}
    values: {nav_order: 2}
  - 
    scope: {path: Funcons-beta/Values/Primitive/Floats}
    values: {nav_order: 3}
  - 
    scope: {path: Funcons-beta/Values/Primitive/Characters}
    values: {nav_order: 4}
  - 
    scope: {path: Funcons-beta/Values/Primitive/Null}
    values: {nav_order: 5}

  # Composite

  - 
    scope: {path: Funcons-beta/Values/Composite/Sequences}
    values: {nav_order: 1}
  
  - # Datatypes
    scope: {path: Funcons-beta/Values/Composite/Datatypes}
    values: {nav_order: 2}
  - 
    scope: {path: Funcons-beta/Values/Composite/Tuples}
    values: {nav_order: 3}
  - 
    scope: {path: Funcons-beta/Values/Composite/Lists}
    values: {nav_order: 4}
  - 
    scope: {path: Funcons-beta/Values/Composite/Strings}
    values: {nav_order: 5}
  - 
    scope: {path: Funcons-beta/Values/Composite/Vectors}
    values: {nav_order: 6}
  - 
    scope: {path: Funcons-beta/Values/Composite/Trees}
    values: {nav_order: 7}
  - 
    scope: {path: Funcons-beta/Values/Composite/References}
    values: {nav_order: 8}
  - 
    scope: {path: Funcons-beta/Values/Composite/Records}
    values: {nav_order: 9}
  - 
    scope: {path: Funcons-beta/Values/Composite/Variants}
    values: {nav_order: 10}
  - 
    scope: {path: Funcons-beta/Values/Composite/Classes}
    values: {nav_order: 11}
  - 
    scope: {path: Funcons-beta/Values/Composite/Objects}
    values: {nav_order: 12}
  - 
    scope: {path: Funcons-beta/Values/Composite/Bits}
    values: {nav_order: 13}
  - # Built-in
    scope: {path: Funcons-beta/Values/Composite/Sets}
    values: {nav_order: 14}
  - 
    scope: {path: Funcons-beta/Values/Composite/Maps}
    values: {nav_order: 15}
  - 
    scope: {path: Funcons-beta/Values/Composite/Multisets}
    values: {nav_order: 16}
  - 
    scope: {path: Funcons-beta/Values/Composite/Graphs}
    values: {nav_order: 17}

  # Abstraction
  
  - 
    scope: {path: Funcons-beta/Values/Abstraction/Generic}
    values: {nav_order: 1}
  - 
    scope: {path: Funcons-beta/Values/Abstraction/Thunks}
    values: {nav_order: 2}
  - 
    scope: {path: Funcons-beta/Values/Abstraction/Functions}
    values: {nav_order: 3}
  - 
    scope: {path: Funcons-beta/Values/Abstraction/Patterns}
    values: {nav_order: 4}
