.PHONY: all

all: docs math kramdown pdflatex

CBS-DIRS   = $(shell find . -type f -name '*.cbs' -exec dirname {} \; )
CBS-FILES  = $(shell find . -type f -name '*.cbs' )

# Generated by make docs
DOCS-FILES = $(CBS-DIRS:%=_docs/%/index.md)

# Generated by make math
MATH-FILES = $(CBS-DIRS:%=_math/%/index.md) $(CBS-FILES:%.cbs=%.tex) $(CBS-FILES:%.cbs=%.md)

# Generatd by make kramdown pdflatex
TEX-FILES  = $(CBS-FILES:%.cbs=%.part.tex)
PDF-FILES  = $(CBS-FILES:%.cbs=%.pdf)
AUX-FILES  = $(CBS-FILES:%.cbs=%.aux)
LOG-FILES  = $(CBS-FILES:%.cbs=%.log)
OUT-FILES  = $(CBS-FILES:%.cbs=%.out)
TOC-FILES  = $(CBS-FILES:%.cbs=%.toc)

.PHONY: clean maintainer-clean

clean:
	rm -f $(AUX-FILES) $(LOG-FILES) $(OUT-FILES) $(TOC-FILES)

maintainer-clean: clean
	rm -f $(DOCS-FILES) $(MATH-FILES) $(TEX-FILES) $(PDF-FILES)

KRAMDOWN = kramdown -o remove_html_tags,latex

PDFLATEX = pdflatex -interaction=batchmode

SUNSHINE = java -Xss16M -jar sunshine2.jar build --language ../cbs-beta-tools/CBS 

DOCS = $(SUNSHINE) --transform-goal "One Doc" --project 

MATH = $(SUNSHINE) --transform-goal "One Math" --project 

# Web pages

.PHONY: serve

serve:
	@-rm -r .jekyll-cache/
	@-rm -r _site/
	bundle exec jekyll serve --config _config.yml,_config_dev.yml --no-watch

.PHONY: funcons languages unstable-funcons unstable-languages docs math
.PHONY: funcons-docs languages-docs unstable-funcons-docs unstable-languages-docs
.PHONY: funcons-math languages-math unstable-funcons-math unstable-languages-math

docs: funcons-docs languages-docs unstable-funcons-docs unstable-languages-docs

math: funcons-math languages-math unstable-funcons-math unstable-languages-math

funcons: funcons-docs funcons-math

languages: languages-docs languages-math
	
unstable-funcons: unstable-funcons-docs unstable-funcons-math

unstable-languages: unstable-languages-docs unstable-languages-math

funcons-docs: 
	@echo docs: Funcons-beta
	@$(DOCS) Funcons-beta

funcons-math:
	@echo math: Funcons-beta
	@$(MATH) Funcons-beta

languages-docs: 
	@echo docs: Languages-beta
	@$(DOCS) Languages-beta/IMP/IMP-cbs
	@$(DOCS) Languages-beta/MiniJava/MiniJava-cbs
	@$(DOCS) Languages-beta/SIMPLE/SIMPLE-cbs
	@$(DOCS) Languages-beta/SL/SL-cbs
	@$(DOCS) Languages-beta/OCaml-Light/OC-L-cbs

languages-math:
	@echo math: Languages-beta
	@$(MATH) Languages-beta/IMP/IMP-cbs
	@$(MATH) Languages-beta/MiniJava/MiniJava-cbs
	@$(MATH) Languages-beta/SIMPLE/SIMPLE-cbs
	@$(MATH) Languages-beta/SL/SL-cbs
	@$(MATH) Languages-beta/OCaml-Light/OC-L-cbs

unstable-funcons-docs: 
	@echo docs: Unstable-Funcons-beta
	@$(DOCS) Unstable-Funcons-beta

unstable-funcons-math:
	@echo math: Unstable-Funcons-beta
	@$(MATH) Unstable-Funcons-beta

unstable-languages-docs: 
	@echo docs: Unstable-Languages-beta
	@$(DOCS) Unstable-Languages-beta/IMP-Plus-Plus/IMPPP-cbs
	@$(DOCS) Unstable-Languages-beta/LangDev-2019/LD-cbs
	@$(DOCS) Unstable-Languages-beta/SIMPLE-Threads/SIMPLE-THR-cbs
	@$(DOCS) Unstable-Languages-beta/Test/TEST-cbs

unstable-languages-math:
	@echo math: Unstable-Languages-beta
	@$(MATH) Unstable-Languages-beta/IMP-Plus-Plus/IMPPP-cbs
	@$(MATH) Unstable-Languages-beta/LangDev-2019/LD-cbs
	@$(MATH) Unstable-Languages-beta/SIMPLE-Threads/SIMPLE-THR-cbs
	@$(MATH) Unstable-Languages-beta/Test/TEST-cbs

# LaTeX and PDFs

# make kramdown: MATH-FILES -> TEX-FILES
# make pdflatex: TEX-FILES  -> PDF-FILES AUX-FILES LOG-FILES OUT-FILES
# make clean: rm AUX-FILES LOG-FILES OUT-FILES TOC-FILES

.PHONY: kramdown pdflatex

kramdown: $(TEX-FILES)
	
%.part.tex: %.md
	@echo kramdown: "$(@F)"
	@$(KRAMDOWN) $< > $@

pdflatex: $(PDF-FILES)

%.pdf: %.tex %.part.tex
	@echo pdflatex: "$(@F)"
	@cd $(@D) \
	&& ($(PDFLATEX) $(<F) > /dev/null) \
	&& ($(PDFLATEX) $(<F) > /dev/null)
